var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/contact/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f7f0193f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_f9cb065a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a97903a9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__9c7dbd46._.js")
R.c("server/chunks/ssr/_d586bcf1._.js")
R.c("server/chunks/ssr/lib_utils_ts_78807e9c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_contact_layout_tsx_9c17aaaf._.js")
R.c("server/chunks/ssr/_next-internal_server_app_contact_page_actions_44e32ac3.js")
R.m(92677)
module.exports=R.m(92677).exports
