var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/p/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k07bv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0c~2wt7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tmbvij._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0_z3oos.js")
R.c("server/chunks/ssr/[root-of-the-server]__0oku6qf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0-iu0c8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0zweu-0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lfcxmo._.js")
R.c("server/chunks/ssr/_0bn.7yp._.js")
R.c("server/chunks/ssr/lib_utils_ts_0ks3cu5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_p_[slug]_page_actions_03tbjh8.js")
R.m(4548)
module.exports=R.m(4548).exports
