var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blog/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3a70ad12._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_2e3c8227._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a97903a9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_174ae28d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__9c7dbd46._.js")
R.c("server/chunks/ssr/_d586bcf1._.js")
R.c("server/chunks/ssr/lib_utils_ts_78807e9c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_blog_layout_tsx_ff46dc5c._.js")
R.c("server/chunks/ssr/_next-internal_server_app_blog_[id]_page_actions_dd81b08e.js")
R.m(88239)
module.exports=R.m(88239).exports
