// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/about" | "/admin" | "/admin/forgot-password" | "/admin/smtp-check" | "/blog" | "/blog/[id]" | "/careers" | "/case-studies/[id]" | "/contact" | "/faqs" | "/news" | "/news/[id]" | "/p/[slug]" | "/privacy" | "/services/[slug]" | "/terms"
type AppRouteHandlerRoutes = "/api/auth/change-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/reset-password" | "/api/auth/session" | "/api/auth/smtp-diagnostic" | "/api/contact" | "/api/content" | "/api/upload"
type PageRoutes = never
type LayoutRoutes = "/" | "/about" | "/admin" | "/blog" | "/careers" | "/contact" | "/faqs" | "/news" | "/privacy" | "/terms"
type RedirectRoutes = "/page"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/about": {}
  "/admin": {}
  "/admin/forgot-password": {}
  "/admin/smtp-check": {}
  "/api/auth/change-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/reset-password": {}
  "/api/auth/session": {}
  "/api/auth/smtp-diagnostic": {}
  "/api/contact": {}
  "/api/content": {}
  "/api/upload": {}
  "/blog": {}
  "/blog/[id]": { "id": string; }
  "/careers": {}
  "/case-studies/[id]": { "id": string; }
  "/contact": {}
  "/faqs": {}
  "/news": {}
  "/news/[id]": { "id": string; }
  "/p/[slug]": { "slug": string; }
  "/page": {}
  "/privacy": {}
  "/services/[slug]": { "slug": string; }
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/admin": never
  "/blog": never
  "/careers": never
  "/contact": never
  "/faqs": never
  "/news": never
  "/privacy": never
  "/terms": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
